/**
 * Read the committed Cohort module cards (open-content/modules/cards/), the
 * mirrored rights-clean md3 cards cohort.md serves as its own `cohort-open`
 * rows. Generated by `content:cohort-mirror-cards --write`; see
 * docs/designs/2026-09-23-cohort-mirror.md (Increment 3).
 *
 * Fail-closed, like the module question loader: the files on disk must be
 * exactly the release, each card must match its released fingerprint, carry
 * only public fields, ship only open-original images and leak nothing. Any
 * error empties the corpus, so a seed can never write half a release.
 */
import fs from 'node:fs';
import path from 'node:path';

import { deriveCardDifficulty } from '@/lib/manifold/difficulty';
import { isOpenFigurePath } from '@/lib/figures/open-figure-access';
import {
  cardShardPath,
  cohortCardServingFingerprint,
  cohortCardServingRow,
  COHORT_MODULE_ROTATION,
  publicCardLeaks,
  type CohortCardRelease,
  type CohortCardShard,
  type PublicMirrorCard,
} from './cohort-mirror-cards';
import { COHORT_DISCIPLINES } from './cohort-mirror';

export const DEFAULT_COHORT_CARD_MODULE_ROOT = path.join(process.cwd(), 'open-content', 'modules');
/** The stableId namespace the card seeder owns; its stale sweep never looks outside it. */
export const COHORT_CARD_STABLE_ID_PREFIX = 'cohort:';

const CARD_KEYS: ReadonlySet<string> = new Set(['id', 'origin', 'discipline', 'cardType', 'sourceComponent', 'front', 'back',
  'context', 'complexity', 'importance', 'variantGroup', 'variantIndex', 'imageUrl', 'imageCaption', 'reference']);
const DISCIPLINES: ReadonlySet<string> = new Set(COHORT_DISCIPLINES);

export interface LoadedCohortCard {
  card: PublicMirrorCard;
  /** Repo-relative shard the card was read from; stored as the row's sourceFile. */
  sourceFile: string;
}

export interface LoadedCohortCards {
  files: string[];
  cards: LoadedCohortCard[];
  errors: string[];
}

function listShards(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true })
    .flatMap((entry) => (entry.isDirectory() ? listShards(path.join(dir, entry.name)) : [path.join(dir, entry.name)]))
    .sort();
}

function cardErrors(card: PublicMirrorCard, shard: CohortCardShard, shardPath: string): string[] {
  const errors: string[] = [];
  for (const key of Object.keys(card)) if (!CARD_KEYS.has(key)) errors.push(`unexpected field ${key}`);
  if (card.cardType !== 'cloze' || typeof card.front !== 'string' || card.front.split('[___]').length !== 2) {
    errors.push('not a single-blank cloze');
  }
  if (typeof card.back !== 'string' || !card.back.trim()) errors.push('empty answer');
  if (card.discipline !== shard.discipline || !DISCIPLINES.has(card.discipline)) errors.push(`discipline ${card.discipline}`);
  try {
    if (cardShardPath(card) !== shardPath) errors.push(`belongs in ${cardShardPath(card)}`);
  } catch (error) {
    errors.push(error instanceof Error ? error.message : String(error));
  }
  if (card.imageUrl && !isOpenFigurePath(card.imageUrl)) errors.push(`image ${card.imageUrl} is not an open original`);
  const leaks = publicCardLeaks(card);
  if (leaks.length > 0) errors.push(`leak: ${leaks.join('; ')}`);
  return errors;
}

export function loadCohortModuleCardsFromDisk(options: { moduleRoot?: string } = {}): LoadedCohortCards {
  const root = options.moduleRoot ?? DEFAULT_COHORT_CARD_MODULE_ROOT;
  const releasePath = path.join(root, 'cards-release-v1.json');
  const shardFiles = listShards(path.join(root, 'cards'));
  const files = [...shardFiles, releasePath].sort();
  const errors: string[] = [];
  const cards: LoadedCohortCard[] = [];

  let release: CohortCardRelease;
  try {
    release = JSON.parse(fs.readFileSync(releasePath, 'utf8')) as CohortCardRelease;
    if (release.schemaVersion !== 1 || !Array.isArray(release.cardIds) || typeof release.cardFingerprints !== 'object' || !release.cardFingerprints) {
      throw new Error('expected schemaVersion 1 with cardIds and cardFingerprints');
    }
  } catch (error) {
    return { files, cards: [], errors: [`${releasePath}: invalid Cohort card release (${error instanceof Error ? error.message : String(error)})`] };
  }

  for (const abs of shardFiles) {
    // Shard paths are reported and checked in their committed, repo-relative form.
    const shardPath = `open-content/modules/${path.relative(root, abs).split(path.sep).join('/')}`;
    let shard: CohortCardShard;
    try {
      shard = JSON.parse(fs.readFileSync(abs, 'utf8')) as CohortCardShard;
      if (shard.schemaVersion !== 1 || shard.licence !== 'CC-BY-4.0' || !Array.isArray(shard.cards)) {
        throw new Error('expected schemaVersion 1, licence CC-BY-4.0 and a cards array');
      }
    } catch (error) {
      errors.push(`${shardPath}: invalid shard (${error instanceof Error ? error.message : String(error)})`);
      continue;
    }
    for (const card of shard.cards) {
      for (const error of cardErrors(card, shard, shardPath)) errors.push(`${shardPath}: ${card.id}: ${error}`);
      cards.push({ card, sourceFile: shardPath });
    }
  }

  const released = new Set(release.cardIds);
  const onDisk = new Map<string, LoadedCohortCard>();
  for (const loaded of cards) {
    if (onDisk.has(loaded.card.id)) errors.push(`${loaded.sourceFile}: duplicate card id ${loaded.card.id}`);
    onDisk.set(loaded.card.id, loaded);
  }
  for (const [id, loaded] of onDisk) {
    if (!released.has(id)) {
      errors.push(`${releasePath}: ${id} is on disk but not in the release`);
      continue;
    }
    if (release.cardFingerprints[id] !== cohortCardServingFingerprint(cohortCardServingRow(loaded.card))) {
      errors.push(`${releasePath}: ${id} serving fingerprint does not match its file (regenerate the release)`);
    }
  }
  for (const id of released) if (!onDisk.has(id)) errors.push(`${releasePath}: ${id} is released but its file is missing`);

  return { files, cards: errors.length === 0 ? cards : [], errors };
}

/** The Card row one public card seeds. Nothing md3-specific: no week, topics, cluster or concept. */
export function cohortCardSeedRow(card: PublicMirrorCard, sourceFile: string) {
  return {
    stableId: card.id,
    cardType: card.cardType,
    rotation: COHORT_MODULE_ROTATION,
    week: null,
    sourceFile,
    sourceComponent: card.sourceComponent,
    front: card.front,
    back: card.back,
    backs: null,
    context: card.context,
    topics: [] as string[],
    difficulty: deriveCardDifficulty({
      cardType: 'cloze',
      complexity: card.complexity as Parameters<typeof deriveCardDifficulty>[0]['complexity'],
      front: card.front,
      back: card.back,
      context: card.context,
    }).label,
    complexity: card.complexity,
    importance: card.importance,
    imageUrl: card.imageUrl ?? null,
    imageCaption: card.imageCaption ?? null,
    imageRole: null,
    moduleNodes: [`cohort/${card.discipline}`],
    conceptId: null,
    clusterId: null,
    variantGroupId: card.variantGroup,
    variantIndex: card.variantIndex,
    variantType: card.variantGroup ? 'cloze-blank' : null,
  };
}
