/**
 * Which CORPUS an item came from, for fair seat allocation in a composed deck.
 *
 * A composed deck (NSx) serves mostly borrowed cards — it owns the Kubie
 * laboratory since 2026-09-16 and still draws the plates and BlueLink from
 * other rotations — and the learner asked for "a mix of cards from the
 * different sources" rather than whichever source the ranker happened to
 * favour.
 *
 * Rotation alone cannot express that. The Netter plates and the Kubie
 * neuroanatomy collection BOTH live in `surgical-sciences`, so a rotation-level
 * round-robin gives two buckets where there are three corpora:
 *
 *   Netter plates   surgical-sciences   2,208 NSx-declared cards
 *   Kubie           surgical-sciences   1,793
 *   BlueLink        anatomy             1,039
 *
 * Nor can it be inferred from `sourceFile`, which is the obvious shortcut and
 * the wrong one: BlueLink is filed one MDX file per anatomical region, so
 * splitting on the filename shatters it into cranial / orbit / brachial / deep
 * and hands each fragment an equal share — starving the two real corpora while
 * looking like fairness. The mapping is therefore explicit and small, the same
 * argument the anatomy curriculum registry makes: a corpus that inherits its
 * identity by accident inherits the wrong one.
 *
 * Unknown rotations fall back to the rotation itself, so a new source is its
 * own corpus and is never silently merged into another's seats.
 */

/** Files generated by the Kubie import, which shares a rotation with the plates. */
const KUBIE_SOURCE_PREFIX = 'kubie-';

export interface CorpusIdentity {
  rotation: string | null | undefined;
  sourceFile?: string | null;
}

export function sourceCorpusFor(item: CorpusIdentity): string {
  const rotation = item.rotation ?? 'unknown';
  if (rotation === 'anatomy') return 'bluelink';
  if (rotation === 'surgical-sciences') {
    return item.sourceFile?.startsWith(KUBIE_SOURCE_PREFIX) ? 'kubie' : 'plates';
  }
  // NSx owns the Kubie laboratory natively since 2026-09-16; the handful of
  // hand-authored nsx-* files ride with it rather than forming a fourth
  // corpus that would take an equal share of seats for a few dozen cards.
  if (rotation === 'neurosurg') return 'kubie';
  return rotation;
}
