/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/generate-deep-dive-cards-manifest.mjs
 */

export interface DeepDiveCardMeta {
  slug: string;
  file: string;
  title: string;
  description: string;
  cardStableId?: string;
  questionId?: string;
  rotation?: string;
  week?: number;
  tags?: string[];
}

export const deepDiveCardMetaBySlug: Record<string, DeepDiveCardMeta> = {
};

export const allDeepDiveCardSlugs = Object.keys(deepDiveCardMetaBySlug);
