/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/generate-deep-dive-cards-manifest.mjs
 */

export interface DeepDiveCardLookup {
  slug: string;
  title: string;
  description: string;
}

export const deepDiveCardByQuestionId: Record<string, DeepDiveCardLookup> = {
};
