/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/generate-deep-dive-manifest.mjs
 */

import type { ComponentType } from 'react';

export interface DeepDiveMeta {
  slug: string;
  file: string;
  title: string;
  description: string;
  duration?: string;
  backLink?: string;
  rotation?: string;
  week?: number;
  tags?: string[];
  hasVideo?: boolean;
}

export const deepDiveMetaBySlug: Record<string, DeepDiveMeta> = {
};

export const deepDiveLoaderBySlug: Record<string, () => Promise<{ default: ComponentType }>> = {
};

export const allDeepDiveSlugs = Object.keys(deepDiveMetaBySlug);
