/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/generate-deep-dive-cards-manifest.mjs
 */

import type { ComponentType } from 'react';

export const deepDiveCardLoaderBySlug: Record<string, () => Promise<{ default: ComponentType }>> = {
};
