-- Unify vertical-specific card/question/progress tables into core Card/Question models.
--
-- NOTE: Run data migrations first:
--   npx tsx scripts/migrations/migrate-gsse-to-core.ts
--   npx tsx scripts/migrations/migrate-anatomy-to-core.ts

-- MCAT
DROP TABLE IF EXISTS "MCATResponse" CASCADE;
DROP TABLE IF EXISTS "MCATProgress" CASCADE;
DROP TABLE IF EXISTS "MCATQuestion" CASCADE;
DROP TABLE IF EXISTS "MCATCard" CASCADE;
DROP TABLE IF EXISTS "MCATTopic" CASCADE;

-- GAMSAT
DROP TABLE IF EXISTS "GAMSATS1Response" CASCADE;
DROP TABLE IF EXISTS "GAMSATS3Response" CASCADE;
DROP TABLE IF EXISTS "GAMSATS1Question" CASCADE;
DROP TABLE IF EXISTS "GAMSATS3Question" CASCADE;
DROP TABLE IF EXISTS "GAMSATS1Passage" CASCADE;
DROP TABLE IF EXISTS "GAMSATS3Passage" CASCADE;
DROP TABLE IF EXISTS "GAMSATS2Sample" CASCADE;
DROP TABLE IF EXISTS "GAMSATS2Prompt" CASCADE;
DROP TABLE IF EXISTS "GAMSATCard" CASCADE;
DROP TABLE IF EXISTS "GAMSATTopic" CASCADE;
DROP TABLE IF EXISTS "GAMSATSection" CASCADE;
DROP TABLE IF EXISTS "GAMSATProgress" CASCADE;

-- ALS
DROP TABLE IF EXISTS "ALSEvent" CASCADE;
DROP TABLE IF EXISTS "ALSSession" CASCADE;
DROP TABLE IF EXISTS "ALSScenario" CASCADE;

-- GSSE
DROP TABLE IF EXISTS "GsseProgress" CASCADE;
DROP TABLE IF EXISTS "GsseConceptMastery" CASCADE;
DROP TABLE IF EXISTS "GsseSpotImage" CASCADE;
DROP TABLE IF EXISTS "GsseCluster" CASCADE;
DROP TABLE IF EXISTS "GsseCard" CASCADE;

-- Anatomy
DROP TABLE IF EXISTS "AnatomyReviewEvent" CASCADE;
DROP TABLE IF EXISTS "AnatomyProgress" CASCADE;
DROP TABLE IF EXISTS "AnatomyMCQProgress" CASCADE;
DROP TABLE IF EXISTS "AnatomyMCQ" CASCADE;
DROP TABLE IF EXISTS "AnatomyFlashcardProgress" CASCADE;
DROP TABLE IF EXISTS "AnatomyFlashcard" CASCADE;
