/**
 * Typed fixtures for the serve-lane tests.
 *
 * These use `satisfies` against the REAL domain types rather than
 * `as unknown as`. `StaticCard` is auto-generated from the content map, so if
 * the generator grows a field, every fixture fails `npm run build` until the
 * field is acknowledged. That tripwire is what was missing on 2026-07-09: the
 * hand-written `makeCard()` omitted `imageUrl`/`imageCaption`/`imageRole`
 * entirely, so no test written against it could catch the instant lane
 * dropping those very fields.
 *
 * Type-only imports from `@/lib/generated/*` — that directory is gitignored and
 * regenerated by `prebuild`, so it must never be a runtime dependency.
 */
import type { StaticCard, StaticQuestion } from '@/lib/generated/content-map-types';
import type { LoadedRotationContent } from '@/lib/study/rotation-content-map';
import type { SessionContext } from '@/lib/study/unified-session-types';

export function makeStaticCard(overrides: Partial<StaticCard> = {}): StaticCard {
  const base = {
    id: 'card-1',
    front: 'Front of card-1 [___].',
    back: 'answer',
    backs: null,
    context: null,
    imageUrl: null,
    imageCaption: null,
    imageRole: null,
    sourceComponent: 'KeyPoint',
    rotation: 'test-rotation',
    week: 1,
    clusterId: null,
    complexity: 1,
    crosslinks: null,
    cardType: 'cloze',
    topics: [],
    difficulty: 'easy',
    variantGroupId: null,
    variantIndex: null,
    variantType: null,
  } satisfies StaticCard;
  return { ...base, ...overrides };
}

export function makeStaticQuestion(overrides: Partial<StaticQuestion> = {}): StaticQuestion {
  const base = {
    id: 'question-1',
    stem: 'Stem of question-1?',
    options: [
      { label: 'A', text: 'Option A', isCorrect: true },
      { label: 'B', text: 'Option B', isCorrect: false },
      { label: 'C', text: 'Option C', isCorrect: false },
      { label: 'D', text: 'Option D', isCorrect: false },
    ],
    context: 'A patient presents.',
    imageUrl: null,
    imageCaption: null,
    rotation: 'test-rotation',
    moduleNodes: [],
    week: 1,
    topics: [],
    difficulty: 'easy',
    combinations: null,
    correctVariants: null,
  } satisfies StaticQuestion;
  return { ...base, ...overrides };
}

export function makeRotationContent(
  cards: StaticCard[],
  questions: StaticQuestion[] = [],
): LoadedRotationContent {
  return {
    cards: Object.fromEntries(cards.map((c) => [c.id, c])),
    questions: Object.fromEntries(questions.map((q) => [q.id, q])),
    cardList: cards,
    questionList: questions,
  };
}

/**
 * Every field of `SessionContext` is named explicitly below (no `as
 * SessionContext` cast) — that's the entire point of this file. Read
 * `src/lib/study/unified-session-types.ts:134-163` before adding a field to
 * `SessionContext`; extend `base` here in the same change or this factory
 * silently drifts back into the pattern it exists to prevent.
 */
export function makeSessionContext(overrides: Partial<SessionContext> = {}): SessionContext {
  const base = {
    sessionId: 'session-1',
    batchId: 'batch-1',
    rotation: 'test-rotation',
    weekFilter: null,
    typeFilter: null,
    difficultyFilter: null,
    topicsFilter: null,
    modulesFilter: null,
    mode: undefined,
    clientExcludeCards: [],
    clientExcludeQuestions: [],
    clientExcludeCardSet: new Set<string>(),
    clientExcludeQuestionSet: new Set<string>(),
    hasClientExclusions: false,
    hasFilters: false,
    noCache: false,
    batchSize: 10,
    rotationContent: makeRotationContent([]),
    userId: 'user-1',
    isGuest: false,
    imageTier: 'standard',
    anonymousSessionId: undefined,
    t0: 0,
    tAuthEnd: 0,
    commitmentLevel: 'browser',
  } satisfies SessionContext;
  return { ...base, ...overrides };
}
