import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Card ↔ question proximity: which MCQs probe what a card teaches.
 *
 * The scheduler's memory model reads self-rated cloze grades and nothing else;
 * objective MCQ outcomes never reach it. Joining the two needs a link between a
 * card and the questions that probe it, and the schema has none — `Card.conceptId`
 * is a jurisdiction-variant marker on 60 cards, `QuestionConcept` has no card
 * side, and the two concept namespaces have zero overlap. Embedding proximity is
 * the link: every card and question has a 3072-d embedding, and the HNSW indexes
 * make a top-k neighbour query cheap.
 *
 * Clusters were considered and rejected as the unit: 872 of them, 1 to 3,699
 * cards each, a third of cards in none. Direct kNN with a floor needs no cluster.
 *
 * TWO FLOORS, read by hand on 2026-09-15 from 200 random live CAH cards × their
 * top-5 CAH questions (see the fixture in the test):
 *
 *   ≥ 0.85  the question probes the SAME FACT the card teaches — stable SVT →
 *           vagal manoeuvres (0.916), spinnaker-sail sign (0.904), growing pains
 *           ↔ growing pains (0.897), UTI prophylaxis for VUR ↔ MCUG for VUR (0.858).
 *   0.78–0.85  the same TOPIC, a different fact — the Noonan dysmorphology card
 *           against Williams and Alagille questions (0.79), UTI prophylaxis against
 *           "what imaging after a first febrile UTI" (0.82). A fair neighbour for
 *           borrowing evidence about a region; not a probe of this card.
 *   < 0.78  noise sharing a rotation and nothing else — grommets for OME against
 *           strep-throat penicillin (0.712) and lobar pneumonia (0.707).
 *
 * Cosine similarity in this space is compressed upward (top-1 median 0.855, rank-5
 * median 0.79), so a round number like 0.5 keeps every pair including the noise.
 * The floors are pinned by the test against the pairs that justified them; move
 * one only with a new read.
 *
 * The overlay is a generated artifact, `content/card-question-proximity.<rotation>.json`,
 * the same shape as `content/card-variant-groups.json`: regenerated by
 * `npm run manifold:proximity`, never hand-edited, keyed by the durable
 * `Card.stableId` and the durable bank question id. No migration.
 */

export const PROXIMITY_TIGHT_FLOOR = 0.85;
export const PROXIMITY_LOOSE_FLOOR = 0.78;
export const PROXIMITY_K = 5;

export interface ProximityLink {
  /** Question id (the durable `bank:<rotation>:<slug>:v<n>` form). */
  q: string;
  /** Cosine similarity, 0–1. */
  sim: number;
}

export interface ProximityOverlay {
  generatedAt: string;
  rotation: string;
  k: number;
  tightFloor: number;
  looseFloor: number;
  /** stableId → links at or above the loose floor, best first. */
  cards: Record<string, ProximityLink[]>;
}

export type ProximityClass = 'tight' | 'loose';

export function classifyProximity(sim: number): ProximityClass | null {
  if (!Number.isFinite(sim)) return null;
  if (sim >= PROXIMITY_TIGHT_FLOOR) return 'tight';
  if (sim >= PROXIMITY_LOOSE_FLOOR) return 'loose';
  return null;
}

export function proximityArtifactPath(rotation: string, root = process.cwd()): string {
  return join(root, 'content', `card-question-proximity.${rotation}.json`);
}

/**
 * Null when the artifact is absent or malformed. A missing overlay is a
 * degraded scheduler (no objective evidence reaches it — today's behaviour);
 * throwing here would be an outage.
 */
export function loadProximityOverlay(
  rotation: string,
  path = proximityArtifactPath(rotation),
): ProximityOverlay | null {
  if (!existsSync(path)) return null;
  try {
    const raw = JSON.parse(readFileSync(path, 'utf-8')) as Partial<ProximityOverlay>;
    if (!raw || typeof raw !== 'object' || !raw.cards || typeof raw.cards !== 'object') return null;
    return {
      generatedAt: String(raw.generatedAt ?? ''),
      rotation: String(raw.rotation ?? rotation),
      k: Number(raw.k ?? PROXIMITY_K),
      tightFloor: Number(raw.tightFloor ?? PROXIMITY_TIGHT_FLOOR),
      looseFloor: Number(raw.looseFloor ?? PROXIMITY_LOOSE_FLOOR),
      cards: raw.cards as Record<string, ProximityLink[]>,
    };
  } catch {
    return null;
  }
}

/**
 * The card's links split by floor, best first. Re-applies the floors on read so
 * an artifact generated with looser settings cannot leak a below-floor link.
 */
export function linksForCard(
  overlay: ProximityOverlay | null,
  stableId: string,
): { tight: ProximityLink[]; loose: ProximityLink[] } {
  const links = overlay?.cards[stableId];
  if (!links || links.length === 0) return { tight: [], loose: [] };
  const tight: ProximityLink[] = [];
  const loose: ProximityLink[] = [];
  for (const link of [...links].sort((a, b) => b.sim - a.sim)) {
    const cls = classifyProximity(link.sim);
    if (cls === 'tight') tight.push(link);
    else if (cls === 'loose') loose.push(link);
  }
  return { tight, loose };
}
